name: My Workflow
run-name: ${{ github.actor }} is testing available api
on: [push]


jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: API
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/installation/repositories
  
