name: My Workflow
on: [push]

permissions:
  issues: write # Grant write access to issues for the entire workflow

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create a comment
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/installation/repositories
  
